name: C/C++ Release candidate ubuntu-GTK3

on:
  push:
    branches:
      - rc
      - debug_ubuntu

jobs:
  build:

    runs-on: ubuntu-20.04

    env:
      EXEC_NAME: "${{ github.event.repository.name }}"
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'rc'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'
    - name: update clock
      run: sudo hwclock -s
    - name: update apt
      run: sudo apt update
    - name: install gtk3
      run: sudo apt install libgtk-3-dev
    - name: install libs
      run: sudo ./BuildLinux.sh -u
    - name: dep cache
      id: cache-action
      uses: actions/cache@v3
      with:
        key: ubu_gtk3_2.7
        path: deps/build/destdir
    - if: steps.cache-action.outputs.cache-hit != 'true'
      name: build deps if new cache
      run: ./BuildLinux.sh -dr -g 3
    - name: slicer, tar & appimage
      run: ./BuildLinux.sh -si -g 3
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rc_${{ github.event.repository.name }}-linux-x64-GTK3.tgz
        path: build/${{ github.event.repository.name }}-linux-x64-GTK3.tgz
    - name: Upload appimage
      uses: actions/upload-artifact@v4
      with:
        name: rc_${{ github.event.repository.name }}-linux-x64-GTK3.AppImage
        path: build/${{ github.event.repository.name }}-linux-x64-GTK3.AppImage
